import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import FilterPatients from "../components/FilterPatients";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pharma Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen min-h-screen">
        <Header />
        <div className="w-full flex justify-center">
          <div className="w-full lg:w-1/2 p-4 pt-20 sm:p-8 sm:pt-20 md:p-20 md:pt-20 lg:pt-32">
            <div className="mb-4">
              <h4>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Quisquam, corporis totam aliquam accusamus aut saepe. Earum,
                assumenda debitis. Molestiae voluptatum odio repellendus ratione
                veritatis. Esse odio ipsam ab eius non!
              </h4>
            </div>
            <FilterPatients />
          </div>
        </div>
      </div>
    </>
  );
}
